### ISSUE TITLE
Compatibility with other LAN adapter versions?

### ISSUE THREAD

**Issue by lucvau** [Frankkkkk/python-daikin-altherma#12]
My Daikin Altherma LAN adapter (BRP069A78) is different from the ones your lib supports (BRP069A61, BRP069A62). I gave it a try anyway with your python-daikin-altherma library but (after a very long delay) got a handshake error - see below. Any chance to make this lib compatible with newer versions of the LAN adapter?
Many thanks!

>>> from daikin_altherma import DaikinAltherma
>>> d = DaikinAltherma('192.168.1.12')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lucva\AppData\Local\Programs\Python\Python310\lib\site-packages\daikin_altherma\__init__.py", line 65, in __init__
    self.ws = create_connection(f"ws://{self.adapter_ip}/mca")
  File "C:\Users\lucva\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 610, in create_connection
    websock.connect(url, **options)
  File "C:\Users\lucva\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 255, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "C:\Users\lucva\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "C:\Users\lucva\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status {status} {message} -+-+- {headers} -+-+- {body}".format(status=status, message=status_message, headers=resp_headers, body=response_body), status, status_message, resp_headers, response_body)
websocket._exceptions.WebSocketBadStatusException: Handshake status 404 Not Found -+-+- {'transfer-encoding': 'chunked', 'content-type': 'text/plain'} -+-+- None
>>>

**Comment by Frankkkkk** [comment]
Indeed, it looks like this is the "cloud ready" version.. Out of curiosity, could you open the web page and show its contents ? Cheers

**Comment by lucvau** [comment]
Hi Frank,Thanks for replying. I found no website at Daikin that allows me to login and control this unit. There is only this “Onecta” app. When I try connecting to the ip address of the LAN adapter, it replies with a dry “File / not found”.I can try my luck and ask Daikin for an API, but that’s rather hopeless. 😟Thanks anyway,LucOp 14 nov 2023 om 12:09 heeft Frank Villaro-Dixon ***@***.***> het volgende geschreven:﻿
Indeed, it looks like this is the "cloud ready" version.. Out of curiosity, could you open the web page and show its contents ? Cheers

**Comment by Jancs-E** [comment]
I would also be happy seeing some solution for data reading by using this adapter
