### ISSUE TITLE
Unable to Connect To BRP069A62 (firmware: 1700390A)

### ISSUE THREAD

**Issue by rfinkers** [Frankkkkk/python-daikin-altherma#13]
Installed the library in a conda environment on an arm Mac; with a recent version of python. 

Adapter, to talk to: BRP069A62
Direct access via HTTP shows me some basic details.

Then just import the library in python (command line) and trying to connect (like the example on the main Page) gives me the following error below.

Some tips on how to proceed?

`
>>> d = DaikinAltherma('http://192.168.XX.XX')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/site-packages/websocket/_http.py", line 172, in _get_addrinfo_list
    addrinfo_list = socket.getaddrinfo(
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/site-packages/daikin_altherma/__init__.py", line 65, in __init__
    self.ws = create_connection(f"ws://{self.adapter_ip}/mca", timeout=2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/site-packages/websocket/_core.py", line 646, in create_connection
    websock.connect(url, **options)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/site-packages/websocket/_http.py", line 133, in connect
    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/daikin/lib/python3.12/site-packages/websocket/_http.py", line 187, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno 8] nodename nor servname provided, or not known
`

**Comment by Frankkkkk** [comment]
**Hello**,
The library needs the __hostname__ (i.e. `192.168.42.13`), and not an URL (what you typed).
Cheers
