### ISSUE TITLE
Problem with heat pumps without domestic hot water

### ISSUE THREAD

**Issue by remy-lavabre** [Frankkkkk/python-daikin-altherma#8]
Good morning,
Executing the python file unfortunately poses a problem each time if the heat pump is not equipped with the domestic hot water tank.
The best would perhaps be to provide an exception checking the error if the heat pump is only used for central heating...?

ERROR:root:Could not get data. Maybe the unit is starting up?
Traceback (most recent call last):
  File "/home/remy/Téléchargements/ESSAI2.py", line 4, in <module>
    d.print_all_status()
  File "/home/remy/.local/lib/python3.10/site-packages/daikin_altherma/__init__.py", line 385, in print_all_status
    Current: {self.tank_temperature}°C (target {self.tank_setpoint_temperature}°C)
  File "/home/remy/.local/lib/python3.10/site-packages/daikin_altherma/__init__.py", line 189, in tank_temperature
    return self._requestValueHP(
  File "/home/remy/.local/lib/python3.10/site-packages/daikin_altherma/__init__.py", line 100, in _requestValueHP
    return self._requestValue(f"MNAE/{item}", output_path, payload)
  File "/home/remy/.local/lib/python3.10/site-packages/daikin_altherma/__init__.py", line 94, in _requestValue
    return dpath.util.get(result, output_path)
  File "/home/remy/.local/lib/python3.10/site-packages/dpath/util.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/remy/.local/lib/python3.10/site-packages/dpath/util.py", line 36, in get
    return dpath.get(obj, glob, separator, default)
  File "/home/remy/.local/lib/python3.10/site-packages/dpath/__init__.py", line 189, in get
    raise KeyError(glob)
KeyError: '/m2m:rsp/pc/m2m:cin/con'

**Comment by Frankkkkk** [comment]
Should be fixed by #14 :)
